# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce59852a5c493fd93c91d2e4fcb11bda28aadb73d629f7f8e6209fd258fd3aeff7a2a45b4837bb98a8e1171d788ae2a52cb044516bc0b77d3048d7d9434835fa

test:
  secret_key_base: 3522aef8ac34a55a473edd9ed97913f3e349f374d7872472ba2d157207edfc6b94c2e55ab9f160e916ebf75fbf2e6948019011375d48256bd1c4e11b6779b391

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
